google:
  auth:
    client-id: 
    hosted-domain: esm.co.jp
  api:
    calendar:
      url: https://www.googleapis.com/calendar/v3/calendars/
      id: japanese__ja@holiday.calendar.google.com
      key: 
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false